### ISSUE TITLE
Merging the two datasets 

### ISSUE THREAD

**Issue by MiroMz** [MIT-Emerging-Talent/2024-group-01-cdsp#11]
After remodeling the datasets to result in a similar format (years as columns), an issue occurs when trying to merge the two datasets. The issue is resulting from having the column Area as an index as well.

**Comment by SujoodEldouma** [comment]
Making the Area column an index as well in the urban data frame resolves this issue, and then you can merge using the following line:

`Agriculture = pd.merge(land, urban, left_index=True, right_index=True)`

**Comment by SujoodEldouma** [comment]
Also, the initial idea was to have comma-separated values (urban, land) per year per country, but after consulting with Evan, it's not very understandable - or easy to understand- so It's better to have a separate column for each indicator per year.
