### ISSUE TITLE
Meeting 2: Problem Identification Converging Stage

### ISSUE THREAD

**Issue by hilaltech** [MIT-Emerging-Talent/2024-group-01-cdsp#2]
**Agenda:** it is a meeting regarding our group status and the converging stage of problem Identification

1. Would like to stay in this group and contribute
2. Join other group( if yes, why)

3. Discussing and finalizing the converging stage of problem identification

**Meeting time:** Tomorrow at 11:00 Am EST time. Google link will be shared

**Comment by SujoodEldouma** [comment]
- [ ]  addition to the agenda:
    - We need to work on the other deliverables for this milestone. 
    - finalize READme, communication.md and pull the other documents to this repo.
    - choosing a name for our group?

**Comment by SujoodEldouma** [comment]
Meeting Minutes:
- Agreed to stay as a team and keep up the great work. xD

- Discussed the ideas proposed and decided to further expand on two of the topics proposed and meet again on Sunday to make an informed decision;
   - Media Analysis
   - Political conflicts' effect on Education

- We need to schedule a check-in with Evan to check whether the methods we want to choose if we decide to go with media analysis are OK.
